name: Release New PyPi Version

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11.x

      - name: Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Upload to PyPI
        env:
          PYPI_ORG_TOKEN: ${{ secrets.PYPI_ORG_TOKEN }}
        run: poetry publish --build -u __token__ -p $PYPI_ORG_TOKEN
